- name: Creating prometheus user group
  group: name="{{groupId}}"
  become: true

- name: Creating prometheus user
  user:
    name: "{{userId}}"
    append: true
    group: "{{groupId}}"
    system: yes
    shell: /usr/sbin/nologin
    comment: "{{userId}} nologin User"
    create_home: false
    state: present

- name: Download and unzip prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy prometheus file to bin
  copy:
    src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
    dest: /usr/local/bin/prometheus
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Delete prometheus tmp folder
  file:
    path: /tmp/prometheus-{{ version }}.linux-amd64
    state: absent

# - name: Creates directory
#   file: 
#     path: /data/prometheus/
#     state: directory
#     owner: "{{userId}}"
#     group: "{{groupId}}"
#     mode: 0755

- name: Creates directory
  file: 
    path: /etc/prometheus/
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755
    
- name: Config file
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: Alert config file
  copy:
    src: "{{ role_path }}/files/alert.yml"
    dest: /etc/prometheus/alert.yml

- name: Copy systemd file
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: systemd_reload

- name: Start prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes
