- name: "Install and config prometheus and grafana"
  hosts: all
  become: true
  # vars:
  #   - node_ip: ""
  #   - grafana_ip: ""
  roles:
    - prometheus
    - grafana

- name: "install and configure Node exporter"
  become: true
  roles:
    - node-exporter