- name: Install and config prometheus and grafana
  hosts: all
  become: true
  # vars:
  #   - node_ip: ""
  #   - grafana_ip: ""
  roles:
    - prometheus
    - grafana

- name: Install and configure Node exporter
  become: true
  roles:
    - node-exporter

- name: Add Ec2 instance public IP
  include_tasks: ec2_ip.yml