- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: event_restart_prometheus

- name: Reload systemd
  uri:
    url: http://localhost:9090/-/reload
    method: POST
    status_code: 200