- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
    enabled: yes
  listen: event_restart_prometheus

- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload